CREATE DATABASE IF NOT EXISTS books_library;
USE books_library;
CREATE TABLE IF NOT EXISTS books
(
    id           INT PRIMARY KEY AUTO_INCREMENT,
    name         VARCHAR(255) UNIQUE ,
    author       VARCHAR(255) DEFAULT NULL,
    release_year VARCHAR(255) DEFAULT NULL,
    pages        VARCHAR(255) DEFAULT NULL,
    description  VARCHAR(255) DEFAULT NULL,
    image        VARCHAR(255) DEFAULT NULL,
    visits       INT     DEFAULT 0,
    wanted       INT     DEFAULT 0,
    deletion     BOOLEAN DEFAULT FALSE
);
INSERT IGNORE INTO books(name, author, release_year, pages, description, image)
VALUES ('СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА', 'Андрей Богуславский', 2003, 351,
        'Лекции и практикум по программированию на Си++', '22.jpg'),
       ('Программирование на языке Go!', 'Марк Саммерфильд', 2010, 290, 'Лекции и практикум по программированию на Go!',
        '23.jpg'),
       ('Толковый словарь сетевых терминов и аббревиатур', 'М., Вильямс', 2007, 410,
        'Толковый словарь сетевых терминов и аббревиатур', '25.jpg'),
       ('Python for Data Analysis', 'Уэс Маккинни', 2011, 327, 'Python for Data Analysis and so on', '26.jpg'),
       ('Thinking in Java (4th Edition)', 'Брюс Эккель', 2000, 378, 'Лекции и практикум по программированию на Java',
        '27.jpg'),
       ('Introduction to Algorithms', 'Томас Кормен', 2005, 315, 'Книга для развития алгоритмического мышления',
        '29.jpg'),
       ('JavaScript Pocket Reference', 'Дэвид Флэнаган', 2012, 263, 'Краткое руководство по JavaScript', '31.jpg'),
       ('Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles', 'Гэри Маклин Холл',
        2006, 336,
        'Лекции и практикум по программированию на С#', '32.jpg'),
       ('SQL: The Complete Reference', 'Джеймс Р. Грофф', 2009, 348, 'Полное руководство по SQL', '33.jpg'),
       ('PHP and MySQL Web Development', 'Люк Веллинг', 2011, 405, 'Разработка при помощи PHP и SQL', '34.jpg'),
       ('Статистический анализ и визуализация данных с помощью R', 'Сергей Мастицкий', 2013, 338,
        'Статистический анализ и визуализация данных с помощью R (что бы это ни было)', '35.jpg'),
       ('Computer Coding for Kid', 'Джон Вудкок', 2015, 235, 'Программирование для детей', '36.jpg'),
       ('Exploring Arduino: Tools and Techniques for Engineering Wizardry', 'Джереми Блум', 2017, 277,
        'Руководство по Arduino для начинающих', '34.jpg'),
       ('Программирование микроконтроллеров для начинающих и не только', 'А. Белов', 2014, 364,
        'Руководство по программированию микроконтроллеров', '38.jpg'),
       ('The Internet of Things', 'Сэмюэл Грингард', 2018, 249, 'Что такое интернет и нафига он нужен', '39.jpg'),
       ('Sketching User Experiences: The Workbook', 'Сет Гринберг', 2017, 268, 'Вообще не понятно что это и для чего',
        '40.jpg'),
       ('InDesign CS6', 'Александр Сераков', 2013, 208, 'Руководство пользователя InDesign', '41.jpg'),
       ('Адаптивный дизайн. Делаем сайты для любых устройств', 'Тим Кедлек', 2015, 293, 'Настольная книга фронтэндщика',
        '42.jpg'),
       ('Android для разработчиков', 'Пол Дейтел', 2019, 315, 'Разработка для устройств Android', '43.jpg'),
       ('Clean Code: A Handbook of Agile Software Craftsmanship', 'Роберт Мартин', 2015, 339, 'Как не писать говнокод',
        '44.jpg'),
       ('Swift Pocket Reference: Programming for iOS and OS X', 'Энтони Грей', 2020, 377,
        'Разработка для устройств на базе iOS and OS X', '45.jpg'),
       ('NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence', 'Мартин Фаулер', 2009, 375,
        'Видимо что-то по SQL', '46.jpg'),
       ('Head First Ruby', 'Джей Макгаврен', 2019, 329, 'Руководство по Ruby для чайников', '47.jpg'),
       ('Practical Vim', 'Дрю Нейл', 2012, 267, 'Вообще не понятно что это и для чего', '48.jpg');
